CREATE TABLE IF NOT EXISTS users (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`username` VARCHAR(50),
	`password` VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS files (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`user` VARCHAR(50),
	`file` VARCHAR(250)
);