CREATE TABLE IF NOT EXISTS users (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`username` VARCHAR(50),
	`password` VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS files (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`user` VARCHAR(50),
	`name` VARCHAR(250),
	`link` VARCHAR(250)
);